### ISSUE TITLE
Cannot add a child to My Kids screen

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#317] opened 2018-11-13 15:20 UTC
In the My Kids screen, the user is not able to add a child to the list.

Steps to Reproduce:
1) Select My Kids.
2) Tap the + icon.
3) Attempt to enter child info.

Expected Results:
Child info can be entered and saved.

Actual Results:
On Android, the info can be added but it does not save.  On iPhone, tapping the info fields has no effect, and no info can be entered.

Tested on iPhone 6s+ Version 11.2.2 (15C202) and Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment] 2018-11-24 17:06
Duplicate of #318

**Closed by rockfordlhotka** 2018-11-24 17:06 UTC
Labels: bug
