### ISSUE TITLE
Android - Contact info cannot be filled out

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#298] opened 2018-10-29 17:07 UTC
In Android, in Basic Details, if the user clicks on the Contact section, nothing happens.

Steps to Reproduce:
1) Tap My Kids.
2) Tap on an existing child in the Child List or create a new entry.
3) Tap on the Contact field (blank space below the word Contact).

Expected Result:
The user is able to enter contact info.

Actual Result:
The field briefly flashes but no info can be entered.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment] 2018-11-10 18:03
Duplicate of #288

**Closed by rockfordlhotka** 2018-11-10 18:03 UTC
Labels: bug
